parser: babel-eslint
extends:
- airbnb-base
env:
  mocha: true
rules:
  max-len:
  - warn
  - code: 120
    ignoreTrailingComments: true
    ignoreUrls: true
  padded-blocks: 0
  react/prop-types: 0
  semi:
  - error
  - never
  space-unary-ops:
  - error
  - overrides:
      "!": true
  quote-props: 0
  no-confusing-arrow: 0
  no-unused-expressions: 0
  no-underscore-dangle:
  - error
  - allow:
    - _id
  import/prefer-default-export: 0
  import/no-extraneous-dependencies:
  - error
  - devDependencies: ["**/*.spec.js", "**//mocha.js"]
ecmaFeatures:
  spread: true
